#%RAML 1.0 Library
annotationTypes:
  ProcessorLocation:
     type: string
     description: Location of your processor
  Id:
    type: string
    description: "Original id of the thing"
  GroupId:
    type: string
  Authors: Author[]
  Version: string
types:
  Author:
    properties:
      name: string
      email: string
      profile: string
